; ; bed.g
; ; called to level the bed
; ;
; ; generated by RepRapFirmware Configuration Tool v3.6.9 on Tue Apr 21 2026 13:49:40 GMT+0100 (British Summer Time)

; ==========================================
; Voron Trident 3-point Z Tramming
; RepRapFirmware 3.6.2
; ==========================================

M290 R0 S0                                          ; Clear baby stepping
M561                                                ; Clear bed transform
M400                                                ; Flush move queue

; Set probe mode if required
M98 P"/macros/szp_mode_normal.g"

; First calibration pass
G30 K0 P0 X30  Y30  Z-99999
G30 K0 P1 X125 Y230 Z-99999
G30 K0 P2 X220 Y30  Z-99999 S3

echo "Initial deviation: " ^ move.calibration.initial.deviation

; Slow probing for maximum repeatability
M558 H2 F300

var iterations = 0
var targetDeviation = 0.005

while move.calibration.initial.deviation > var.targetDeviation

if var.iterations >= 5
    echo "WARNING: Tramming failed to converge after " ^ var.iterations ^ " passes"
    echo "Final deviation: " ^ move.calibration.initial.deviation
    break

set var.iterations = var.iterations + 1

echo "Tramming pass " ^ var.iterations
echo "Deviation before pass: "^ move.calibration.initial.deviation

M98 P"/macros/szp_mode_normal.g"

G30 K0 P0 X30  Y30  Z-99999
G30 K0 P1 X125 Y230 Z-99999
G30 K0 P2 X220 Y30  Z-99999 S3

echo "Tramming complete"
echo "Final deviation: " ^ move.calibration.initial.deviation

; Raise nozzle clear of bed
G1 X125 Y125 Z10 F18000

; Restore normal probe speed
M558 F18000

; Re-home Z after tramming
G28 Z

