; Configuration file for RepRapFirmware on Duet 3 Mini 5+ WiFi
; executed by the firmware on start-up
;
; generated by RepRapFirmware Configuration Tool v3.6.9 on Tue Apr 21 2026 13:49:40 GMT+0100 (British Summer Time)


;==================================                 ;
; General                                           ;
;==================================                 ;
G90                                                 ; absolute coordinates
M83                                                 ; relative extruder moves
M550 P"TridentRRF"                                  ; set hostname
M669 K1                                             ; configure CoreXY kinematics
G4 S5   				                            ; wait 5s for expansion boards to start

;==================================                 ;
; Display                                           ;
;==================================                 ;
M575 P2 S1 B57600                                   ; configure PanelDue support

;==================================                 ;
; Network                                           ;
;==================================                 ;
M552 S1                                             ; configure WiFi adapter
M586 P0 S1                                          ; configure HTTP

;==================================                 ;
; Drives                                            ;
;==================================                 ;
; B/A     _____             _____                   ;
;         |0.0|             |0.1|                   ;
;          ---               ---                    ;
M569 P0.0 S0 D2                                     ; driver 0.0 goes forwards (B axis) using default driver timings in Spreadcycle
M569 P0.1 S0 D2                                     ; driver 0.1 goes forwards (A axis) using default driver timings in Spreadcycle

; Z axis _____                                      ;    
;        |0.3|                                      ;
;    _____---_____                                  ;    
;    |0.2|   |0.4|                                  ;
;     ---     ---                                   ;
M569 P0.2 S0 D3                                     ; driver 0.2 goes forwards (Z axis) using default driver timings in Stealthchop
M569 P0.3 S0 D3                                     ; driver 0.3 goes forwards (Z axis) using default driver timings in Stealthchop
M569 P0.4 S0 D3                                     ; driver 0.4 goes forwards (Z axis) using default driver timings in Stealthchop

; E axis _____                                      ;
;       |124.0|                                     ;
;         ---                                       ;
;         \ /                                       ;
M569 P124.0 S1 D2                                   ; driver 124.0 goes backwards (extruder 0) using default driver timings in Spreadcycle
;M569 P0.7 S1 D2                                    ; driver 0.6 goes forwards (extruder 0) using default driver timings in Spreadcycle

M584 X0.0 Y0.1 Z0.2:0.3:0.4                         ; set axis mapping
M350 X16 Y16 Z16 I1                                 ; configure microstepping with interpolation
M92 X80 Y80 Z400                                    ; configure steps per mm

;==================================                 ;
; Extruder                                          ;
;==================================                 ;
M584 E124.0                                         ; set extruder mapping
M350 E16 I1                                         ; configure microstepping with interpolation
M906 E700                                           ; set extruder driver currents
M92 E900                                            ; configure steps per mm
M566 E300                                           ; set maximum instantaneous speed changes (mm/min)
M203 E7200                                          ; set maximum speeds (mm/min)
M201 E2000                                          ; set accelerations (mm/s^2)

;==================================                 ;
; Axis Limits                                       ;
;==================================                 ;
M208 X0:250 Y0:263 Z0:240                           ; set minimum and maximum axis limits

;==================================                 ;
; Speeds                                            ;
;==================================                 ;
M566 X500 Y500 Z120                                 ; set maximum instantaneous speed changes (mm/min)
M203 X18000.00 Y18000.00 Z800.00                    ; set maximum speeds (mm/min)
M201 X5000.00 Y5000.00 Z250.00                      ; set accelerations (mm/s^2)
M906 X1000 Y1000 Z900                               ; set axis driver currents

;==================================                 ;
; Idle Current Reduction                            ;
;==================================                 ;
M906 I30 T30                                        ; set motor current idle factor & timeout

;==================================                 ;
; Scanning Z probe                                  ;
;==================================                 ; X/Y endstop on Voron pcb w/cable X+gnd to io1 Y to io2 -No voltage
;M558 K0 P5 C"io1.in" H5 F800:200 T12000            ; configure digital probe via slot #0

M558 K0 P11 C"124.i2c.ldc1612" F18000 T9000         ; K0 = primary probe, K1 = secondary probe
G31 K0 X0 Y25 Z2.00                                 ; set Z probe trigger value, offset and trigger height
M671 X-50:125:300 Y18:298:18 S5                     ; define positions of Z leadscrews or bed levelling screws -VORON Trident 250 bed.
M98 P"/macros/szp_mode_normal.g"                    ; this is optional, just here to calm you down when opening DWC, which would show probe 999999 values otherwise.

;==================================                 ;
; Endstops                                          ;
;==================================                 ; X/Y endstop on Voron pcb w/cable X+gnd to io1 Y to io2 -No voltage
M574 S1 X2 P"io5.in"                                ; configure X axis endstop
M574 S1 Y2 P"io6.in"                                ; configure Y axis endstop
;M574 S2 Z1                                         ; configure Z axis endstop

;==================================                 ;
; Mesh Bed Compensation                             ;
;==================================                 ;
M557 X20:230 Y30:240 P5:5                           ; define grid for mesh bed compensation

;==================================                                     ;
; Temp Sensors                                                          ;
;==================================                                     ;
M308 S2 P"temp1" Y"thermistor" A"Chamber Top" T100000 B3950             ; configure sensor #1
M308 A"SZP coil" S10 Y"thermistor" P"124.temp1" T100000 B4092           ; thermistor on PCB/coil

;==================================                                     ;
; Accelerometer                                                         ;
;==================================                                     ;
M955 P124.0 I16

;==================================                                     ;
; Heaters                                                               ;
;==================================                                     ;
; Heated bed                                                            ;
M308 S0 P"temp0" Y"thermistor" T100000 B3950 A"Bed"                     ; configure sensor 0 as thermistor on pin ADC_0
M950 H0 C"out2" T0 Q50                                                  ; create bed heater output on bed and map it to sensor 0
M307 H0 B0 S1.00                                                        ; disable bang-bang mode for the bed heater and set PWM limit
M140 H0                                                                 ; map heated bed to heater 0
M143 H0 S120                                                            ; set temperature limit for heater 0 to 120C

; Tool 0 heater
M308 S1 P"124.temp0" Y"thermistor" A"Revo" T100000 B4725 C7.06e-8    ; configure sensor 1 as thermistor on pin temp1
M950 H1 C"124.out0" T1                                      	        ; create nozzle heater output on out1 and map it to sensor 1
M307 H1 B0 S1.00                                         		      	; disable bang-bang mode for heater  and set PWM limit
M143 H1 S300                                              		      	; set temperature limit for heater 1 to 300C

;==================================                 ;
; Fans                                              ;
;==================================                 ;
M950 F0 C"io1.out" Q2000                            ; create fan #0
M106 P0 C"CPAP Fan" S0 H-1 L0.20 X1.0 B0.1          ; configure fan #0

M950 F1 C"124.out2"                                 ; create fan #1
M106 P1 C"Heatsink Fan" S0 X1 B0.1 H1 T45           ; configure fan #1

M950 F2 C"out5"                                     ; GDSTIME 24v out 5
M106 P2 C"Electronics Fans" H0 L0.8 T35:100         ; configure fan #2

;==================================                 ;
; Tools                                             ;
;==================================                 ;
M563 P0 S"Tool 0" D0 H1 F0                          ; create tool #0
M568 P0 R0 S0                                       ; set initial tool #0 active and standby temperatures to 0C

;==================================                 ;
; Lights                                            ;
;==================================                 ;
M950 F5 C"out1" Q500                                ; create a chamber LED strip on the OUT1 port and set SPI frequency to 3MHz
M106 P5 H-1 L64.0 X192.0 C"Lights"                  ;

M950 E0 C"124.rgbled" T1                            ; create a RGB Neopixel LED strip on the SHT36 port and set SPI frequency to 3MHz
M150 E0 R0 B0 U0 P0 S3 F0                           ; zero out the lights
M150 E0 R0 U0 B128 P128 S1 F1                       ; set the voron symbol blue
M150 E0 R128 B128 U128 P128 S2 F0                   ; set nozzles leds white

M950 E1 C"led" U8                                   ; create a RGB Neopixel LED strip on the LED port and set SPI frequency to 3MHz
M150 E1 R0 U0 B255 P128 S8 F0                       ; set underglow leds to blue

;==================================                 ;
; Board Sensors                                     ;
;==================================                 ;
M308 S3 A"Big Dipper" Y"mcu-temp"                   ; Sensor 3 Built in temp monitor in STM32H7
M308 S4 A"SHT36" Y"mcu-temp" P"124.dummy"           ; Sensor 4 Built in temp monitor in RP2040

;==================================                 ;
; Miscellaneous                                     ;
;==================================                 ;
M572 D0 S0.025										; Pressure Advance for Tool 0
M593 P"ei2" F39 S0.1								; input shaping

T0                                                  ; select first tool
M501									            ; Call config_override.g
M912 P0 S-6 							            ; Calibrate MCU Temperature
G29 S2							    	            ; Disable mesh
M98 P"/macros/05_Light 25%"                         ; set chamber lights to 25%