; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.6.9 on Tue Apr 21 2026 13:49:42 GMT+0100 (British Summer Time)

;G92 X0 ; set X=0
;M118 L1 P0 S"Warning: X is NOT homed but its position has been set to 0."
M98 P"/macros/sb_leds" S"homing"
G92 X0

if !move.axes[1].homed
	; raise Z a bit
	G91
	G1 H2 Z5 F2400
	G90


M913 X75 Y75 ; lower the power bucuse we have been burned.

; Move quickly to X axis endstop and stop there (first pass)
G91
G1 X355 F6000 H1
; Go back a few mm
;M119
G1 X-5 F8000
; Move slowly to X axis endstop once more (second pass)
G1 X10 F255 H1
G90
M913 X100 Y100; back to full power