; pause.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.6.9 on Tue Apr 21 2026 13:49:43 GMT+0100 (British Summer Time)
M83 ; relative extruder moves
G1 E-5 F3600 ; retract 10mm of filament
G91 ; relative positioning
G1 Z5 F360 ; lift Z by 5mm
G90 ; absolute positioning
G1 X5 Y5 F6000 ; go to X=5 Y=5
